2025-02-26 22:26:07,929 | INFO | db_service.py:38 |Connected to the database rag_database
